version: "3.7"

services:
  cassandra-seed:
    container_name: cassandra-seed
    image: cassandra:3.11.6
    environment:
      HEAP_NEWSIZE: 100M
      MAX_HEAP_SIZE: 400M
    ports:
      - 9042:9042
      - 7199:7199
      - 9160:9160

  cassandra-node:
    container_name: cassandra-node
    image: cassandra:3.11.6
    command: /bin/bash -c "sleep 20 && /docker-entrypoint.sh cassandra -f"
    environment:
      CASSANDRA_SEEDS: cassandra-seed
      HEAP_NEWSIZE: 100M
      MAX_HEAP_SIZE: 400M
    depends_on:
      - cassandra-seed

  redis:
    container_name: redis
    image: redis:5.0.8
    ports:
      - 6379:6379

  spark-master:
    container_name: spark-master
    hostname: spark-master
    build:
      context: spark
    image: spark:latest
    command: /bin/bash -c "./start-master.sh"
    ports:
      - 4040:4040
      - 7077:7077
      - 8080:8080

  spark-worker:
    container_name: spark-worker
    image: spark:latest
    command: /bin/bash -c "./start-worker.sh spark-master"
    ports:
      - 8081:8081
      - 4041:4040
    depends_on:
      - spark-master

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.14
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2181

  kafka-seed:
    container_name: kafka-seed
    build:
      context: kafka
    image: kafka:latest
    ports:
      - 9092:9092
    environment:
      BROKER_ID: 0
      ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper

  kafka-broker:
    container_name: kafka-broker
    image: kafka:latest
    ports:
      - 9093:9092
    environment:
      BROKER_ID: 1
      ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka-seed

  kafka-init:
    container_name: kafka-init
    image: kafka:latest
    command: /bin/bash -c "./init-cluster.sh kafka-seed"
    depends_on:
      - kafka-broker

  fraud-detector-service:
    container_name: fraud-detector-service
    build:
      context: fraud-detector-service
    image: fraud-detector-service:latest
    ports:
      - 4444:4040
    environment:
      KAFKA: kafka-seed:9092
      SPARK: spark-master:7077
      REDIS: redis:6379
      CASSANDRA: cassandra-seed:9042
    depends_on:
      - kafka-init
      - spark-master
      - redis
      - cassandra-seed

  fraud-detector-ui:
    container_name: fraud-detector-ui
    build:
      context: fraud-detector-ui
    image: fraud-detector-ui:latest
    ports:
      - 5000:5000
    environment:
      KAFKA: kafka-seed:9092
      REDIS: redis:6379
      CASSANDRA: cassandra-seed:9042
    depends_on:
      - kafka-init
      - spark-master
      - redis
      - cassandra-seed
